/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as DashboardDashboardIndexRouteImport } from './routes/dashboard/dashboard/index'
import { Route as DashboardDashboardUsersRouteImport } from './routes/dashboard/dashboard/users'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/dashboard/dashboard/settings'
import { Route as DashboardDashboardProfileRouteImport } from './routes/dashboard/dashboard/profile'
import { Route as DashboardDashboardDeliveriesRouteImport } from './routes/dashboard/dashboard/Deliveries'
import { Route as DashboardDashboardCustomerPaymentsRouteImport } from './routes/dashboard/dashboard/customer/payments'
import { Route as DashboardDashboardCustomerOrdersRouteImport } from './routes/dashboard/dashboard/customer/orders'
import { Route as DashboardDashboardCustomerCartRouteImport } from './routes/dashboard/dashboard/customer/cart'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardUsersRoute = DashboardDashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardProfileRoute =
  DashboardDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardDeliveriesRoute =
  DashboardDashboardDeliveriesRouteImport.update({
    id: '/Deliveries',
    path: '/Deliveries',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCustomerPaymentsRoute =
  DashboardDashboardCustomerPaymentsRouteImport.update({
    id: '/customer/payments',
    path: '/customer/payments',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCustomerOrdersRoute =
  DashboardDashboardCustomerOrdersRouteImport.update({
    id: '/customer/orders',
    path: '/customer/orders',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardCustomerCartRoute =
  DashboardDashboardCustomerCartRouteImport.update({
    id: '/customer/cart',
    path: '/customer/cart',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/dashboard/Deliveries': typeof DashboardDashboardDeliveriesRoute
  '/dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/dashboard/users': typeof DashboardDashboardUsersRoute
  '/dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/dashboard/customer/cart': typeof DashboardDashboardCustomerCartRoute
  '/dashboard/dashboard/customer/orders': typeof DashboardDashboardCustomerOrdersRoute
  '/dashboard/dashboard/customer/payments': typeof DashboardDashboardCustomerPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/dashboard/Deliveries': typeof DashboardDashboardDeliveriesRoute
  '/dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/dashboard/users': typeof DashboardDashboardUsersRoute
  '/dashboard/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/dashboard/customer/cart': typeof DashboardDashboardCustomerCartRoute
  '/dashboard/dashboard/customer/orders': typeof DashboardDashboardCustomerOrdersRoute
  '/dashboard/dashboard/customer/payments': typeof DashboardDashboardCustomerPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/dashboard/dashboard/Deliveries': typeof DashboardDashboardDeliveriesRoute
  '/dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/dashboard/users': typeof DashboardDashboardUsersRoute
  '/dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/dashboard/customer/cart': typeof DashboardDashboardCustomerCartRoute
  '/dashboard/dashboard/customer/orders': typeof DashboardDashboardCustomerOrdersRoute
  '/dashboard/dashboard/customer/payments': typeof DashboardDashboardCustomerPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/login'
    | '/register'
    | '/dashboard/dashboard'
    | '/dashboard/dashboard/Deliveries'
    | '/dashboard/dashboard/profile'
    | '/dashboard/dashboard/settings'
    | '/dashboard/dashboard/users'
    | '/dashboard/dashboard/'
    | '/dashboard/dashboard/customer/cart'
    | '/dashboard/dashboard/customer/orders'
    | '/dashboard/dashboard/customer/payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/login'
    | '/register'
    | '/dashboard/dashboard/Deliveries'
    | '/dashboard/dashboard/profile'
    | '/dashboard/dashboard/settings'
    | '/dashboard/dashboard/users'
    | '/dashboard/dashboard'
    | '/dashboard/dashboard/customer/cart'
    | '/dashboard/dashboard/customer/orders'
    | '/dashboard/dashboard/customer/payments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/login'
    | '/register'
    | '/dashboard/dashboard'
    | '/dashboard/dashboard/Deliveries'
    | '/dashboard/dashboard/profile'
    | '/dashboard/dashboard/settings'
    | '/dashboard/dashboard/users'
    | '/dashboard/dashboard/'
    | '/dashboard/dashboard/customer/cart'
    | '/dashboard/dashboard/customer/orders'
    | '/dashboard/dashboard/customer/payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard': {
      id: '/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard/': {
      id: '/dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/users': {
      id: '/dashboard/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/dashboard/users'
      preLoaderRoute: typeof DashboardDashboardUsersRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/settings': {
      id: '/dashboard/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/profile': {
      id: '/dashboard/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardProfileRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/Deliveries': {
      id: '/dashboard/dashboard/Deliveries'
      path: '/Deliveries'
      fullPath: '/dashboard/dashboard/Deliveries'
      preLoaderRoute: typeof DashboardDashboardDeliveriesRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/customer/payments': {
      id: '/dashboard/dashboard/customer/payments'
      path: '/customer/payments'
      fullPath: '/dashboard/dashboard/customer/payments'
      preLoaderRoute: typeof DashboardDashboardCustomerPaymentsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/customer/orders': {
      id: '/dashboard/dashboard/customer/orders'
      path: '/customer/orders'
      fullPath: '/dashboard/dashboard/customer/orders'
      preLoaderRoute: typeof DashboardDashboardCustomerOrdersRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/dashboard/dashboard/customer/cart': {
      id: '/dashboard/dashboard/customer/cart'
      path: '/customer/cart'
      fullPath: '/dashboard/dashboard/customer/cart'
      preLoaderRoute: typeof DashboardDashboardCustomerCartRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
  }
}

interface DashboardDashboardRouteChildren {
  DashboardDashboardDeliveriesRoute: typeof DashboardDashboardDeliveriesRoute
  DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardUsersRoute: typeof DashboardDashboardUsersRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardCustomerCartRoute: typeof DashboardDashboardCustomerCartRoute
  DashboardDashboardCustomerOrdersRoute: typeof DashboardDashboardCustomerOrdersRoute
  DashboardDashboardCustomerPaymentsRoute: typeof DashboardDashboardCustomerPaymentsRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardDeliveriesRoute: DashboardDashboardDeliveriesRoute,
  DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardUsersRoute: DashboardDashboardUsersRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardCustomerCartRoute: DashboardDashboardCustomerCartRoute,
  DashboardDashboardCustomerOrdersRoute: DashboardDashboardCustomerOrdersRoute,
  DashboardDashboardCustomerPaymentsRoute:
    DashboardDashboardCustomerPaymentsRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
